# Generated by Django 3.2.3 on 2021-05-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
    ]
