# Generated by Django 3.2.3 on 2021-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_voted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
